# Generated by Django 5.0.4 on 2024-04-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('png_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image_size', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toto_sperky_web.category')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ('-created',),
            },
        ),
    ]
