# Generated by Django 5.0.4 on 2024-04-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='png_image',
        ),
    ]
