# Generated by Django 5.0.4 on 2024-05-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0009_alter_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
