# Generated by Django 5.0.4 on 2024-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0010_product_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='progress',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
