# Generated by Django 5.0.4 on 2024-05-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0011_alter_product_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='progress',
        ),
    ]
