# Generated by Django 5.0.4 on 2024-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0016_product_image_thumbnail_product_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
