# Generated by Django 5.0.4 on 2024-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0019_alter_blog_options_blogimage_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
