# Generated by Django 5.1.2 on 2024-11-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0021_category_created_category_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_webm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
