# Generated by Django 4.2.11 on 2026-01-25 11:42

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0022_product_video_webm'),
    ]

    operations = [
        # AddField pre progress odstránený - stĺpec už existuje v databáze
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Obsah'),
        ),
    ]
