# Generated by Django 4.2.11 on 2026-01-25 18:36

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toto_sperky_web', '0023_product_progress_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Popis'),
        ),
    ]
